### ISSUE TITLE
Fix svg sprite watcher error

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Front-End-Toolkit#55] opened 2016-03-24 11:47 UTC
SVG sprite watcher generates wrong map if svg file is changed.

**Comment by VaclovasV** [comment] 2016-03-24 11:48
why this is happening and how to fix it, you can find here: 
https://github.com/jkphl/gulp-svg-sprite/issues/32

**Comment by VaclovasV** [comment] 2016-03-24 12:35
Duplicate of https://github.com/devbridge/Front-End-Toolkit/issues/49

**Comment by VaclovasV** [comment] 2018-01-05 13:54
Fixed in v2-dev

**Closed by VaclovasV** 2018-01-05 13:54 UTC
Labels: bug, duplicate, Starter Template
